[project]
name = "mcp-kafka"
version = "0.1.0"
description = "A Model Context Protocol (MCP) server for performing Kafka client operations from AI assistants."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
